### ISSUE TITLE
Null Pointer Exception on button tap if Bluetooth is not enabled (Flic Manger)

### ISSUE THREAD

**Issue by sachinrana028** [50ButtonsEach/flic2lib-android-sample#1]
02-17 13:05:17.490 6071-6071/flic.io.flic2androidsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: flic.io.flic2androidsample, PID: 6071
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference
        at io.flic.flic2libandroid.Flic2Manager$5.run(Flic2Manager.java:503)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Emill** [comment]
Hi. What phone or tablet model are you using?

**Comment by sachinrana028** [comment]
Nexus 5 (API 23) emulator.

**Comment by Emill** [comment]
It seems this happens when Bluetooth is not supported on the device, rather than Bluetooth is not enabled. Does that seem correct?

**Comment by sachinrana028** [comment]
Device support Bluetooth but its not enabled.  I will try on real device and let you know accordingly.

**Comment by Emill** [comment]
I'll change so that a proper error message is delivered to the callback instead of crashing in the next release.

**Comment by Emill** [comment]
Fixed.
